# Generated by Django 6.0.3 on 2026-05-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_medicalreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
